image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - test
  - build
  - release

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKERHUB_RELEASE: $DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA
  DOCKERHUB_LATEST: $DOCKERHUB_PROJECT:latest

hadolint:
  stage: test
  image: hadolint/hadolint
  before_script:
    - hadolint --version
  script:
    - hadolint Dockerfile

build:
  stage: build
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $TEST_IMAGE ./
    - docker push $TEST_IMAGE

release:
  stage: release
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker tag $TEST_IMAGE $LATEST_IMAGE
    - docker push $RELEASE_IMAGE
    - docker push $LATEST_IMAGE
  only:
    - master

release-dockerhub:
  stage: release
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $DOCKERHUB_RELEASE
    - docker tag $TEST_IMAGE $DOCKERHUB_LATEST
    - docker push $DOCKERHUB_RELEASE
    - docker push $DOCKERHUB_LATEST
  only:
    - master
